name: deploy

on:
  push:
    branches:
    - main

permissions: write-all
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR: Deploy Action
      COMMIT_AUTHOR_EMAIL: action@github.com

    steps:
    - name: Checkout Repo ⚡️
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install npm dependencies and build
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
